FROM python:2.7

MAINTAINER Shahbaz Nazir "shahbaznazir1992@gmail.com"

# Copying the requirements for installation to take
# advantage of the caching.
COPY tgc/ /tgcapp/tgc/
COPY setup.py /tgcapp
COPY run_tests.sh /tgcapp

WORKDIR /tgcapp

RUN chmod +x run_tests.sh
RUN pip install -r /tgcapp/tgc/requirements.txt

CMD ["./run_tests.sh"]
