- name: Post-deployment tests are run
  shell: docker-compose \
    -f docker-compose-test.yml \
    run --rm \
    -e DOMAIN={{ ip }} \
    integ
  args:
    chdir: "{{ repo_dir }}"
  tags: [service, tests]

#- name: Log into DockerHub
#  docker_login:
#    username: "{{ docker_username }}"
#    password: "{{ docker_pass }}"
#    registry: "{{ registry_url }}"

#- name: Build Container is pushed
#  shell: docker push \
#    "https://hub.docker.com/r/{{ registry_url }}"
#  tags: [service, tests]
