- name: Tests container is built
  shell: docker build \
    -t {{ registry_url }}:test \
    -f Dockerfile.test \
    .
  args:
    chdir: "{{ repo_dir }}"
  tags: [service, tests]

- name: Pre-deployment tests are run
  shell: docker-compose \
    -f docker-compose-test.yml \
    run --rm \
    test
  args:
    chdir: "{{ repo_dir }}"
  tags: [service, tests]

- name: Container is built
  shell: docker build \
    -t shahbazn/shahbazn-tgc \
    .
  args:
    chdir: "{{ repo_dir }}"
  tags: [service]
