server:
  restart: always
  image: nginx
  volumes:
    - /tgc/etc/nginx:/etc/nginx/conf.d
  links:
    - web:web
  ports:
    - "80:80"

web:
  restart: always
  image: shahbazn/shahbazn-tgc:0.1.3
  volumes:
    - /tgc/logs:/tgc/logs
  expose:
    - "8000"
  command: gunicorn tgc:app -b :8000 --name app --log-level=debug --log-file=/tgc/logs/tgc.log

test:
  links:
    - server:server
  image: shahbazn/shahbazn-tgc:0.1.3-test
  environment: 
    TEST_TYPE: integ 
